"""Create recents table

Revision ID: 26f7e104e60b
Revises: a35efbc8e215
Create Date: 2024-05-30 16:48:07.305119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f7e104e60b'
down_revision: Union[str, None] = 'a35efbc8e215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('best', sa.JSON(), nullable=True),
    sa.Column('top', sa.JSON(), nullable=True),
    sa.Column('new', sa.JSON(), nullable=True),
    sa.Column('show', sa.JSON(), nullable=True),
    sa.Column('ask', sa.JSON(), nullable=True),
    sa.Column('job', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recents_id'), 'recents', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recents_id'), table_name='recents')
    op.drop_table('recents')
    # ### end Alembic commands ###
