"""create top articles

Revision ID: a35efbc8e215
Revises: 372bb16d9a66
Create Date: 2024-05-30 16:04:31.852631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35efbc8e215'
down_revision: Union[str, None] = '372bb16d9a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('top_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('by', sa.String(length=255), nullable=True),
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('dead', sa.Boolean(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('poll', sa.Integer(), nullable=True),
    sa.Column('kids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('parts', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('descendants', sa.Integer(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_best_articles_id'), 'best_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_articles_id'), table_name='top_articles')
    op.drop_table('top_articles')
    # ### end Alembic commands ###
